{{- if .Values.certificate.create }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "istioctl-proxy.fullname" . }}
  labels:
    {{- include "istioctl-proxy.labels" . | nindent 4 }}
spec:
  commonName: istioctl-proxy.{{ .Release.Namespace }}.svc
  secretName: {{ include "istioctl-proxy.fullname" . }}
  {{- with .Values.certificate }}
  duration: {{ .duration }}
  renewBefore: {{ .renewBefore }}
  privateKey: {{ .privateKey | toYaml | nindent 4 }}
  revisionHistoryLimit: 1
  issuerRef: {{ .issuerRef | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
