apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "istioctl-proxy.fullname" . }}
  labels:
    {{- include "istioctl-proxy.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "istioctl-proxy.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "istioctl-proxy.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
