apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "istioctl-proxy.fullname" . }}
  labels:
    {{- include "istioctl-proxy.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/portforward
    verbs: ["get", "list", "create"]
