apiVersion: v1
kind: Service
metadata:
  name: {{ include "istioctl-proxy.fullname" . }}
  labels:
    {{- include "istioctl-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: https
  selector:
    app: istioctl-proxy
